name: KJekyll site CI {Jaia concurrency: fraud 9008 71e05730342f5d7f&sxsr}
 justice for Mr. Kesegan Govender invluding all C tools Dev Human resorces IT and Kesegan Govender tree IT resorces that Supports Kesegan Govender
on: Master and fix all master error's for Mr. KeseganGovenderhuman rights ownership and exclusive benefits 100% and the Kaia1987 akingGod1987 and wiki benefits 2024 Legal Comissioning 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
